CREATE TABLE [dbo].[AuditLogs]
(
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,

    [UserId] UNIQUEIDENTIFIER NULL,

    [Action] NVARCHAR(200) NOT NULL,

    [Timestamp] DATETIME2 NOT NULL,

    [IP] NVARCHAR(100) NULL
);